services:
  cube:
    image: cubejs/cube:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "15432:15432"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      CUBEJS_DEV_MODE: true
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_HOST: 187.127.189.166
      CUBEJS_DB_PORT: ${CUBEJS_DB_PORT:-5432}
      CUBEJS_DB_NAME: ${CUBEJS_DB_NAME:-tradebase}
      CUBEJS_DB_USER: ${CUBEJS_DB_USER:-postgres}
      CUBEJS_DB_PASS: postgres
      CUBEJS_API_SECRET: ${CUBEJS_API_SECRET}
    volumes:
      - ./cube:/cube/conf
    networks:
      - tradebase_net
  superset:
    image: amancevice/superset:6.0.0
    container_name: superset
    restart: unless-stopped
    ports:
      - "7088:8088"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=superset-postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py:ro
    depends_on:
      - superset-postgres
      - superset-redis
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset init &&
        gunicorn --bind 0.0.0.0:8088 --workers 4 --worker-class gthread --threads 20 --timeout 120 'superset.app:create_app()'
      "
